// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/create-comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-comment').default>>>>
    }
    '/api/create-post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-post').default>>>>
    }
    '/api/delete-comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delete-comment').default>>>>
    }
    '/api/delete-post/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/delete-post/[id]').default>>>>
    }
    '/api/get-all-posts': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/get-all-posts').default>>>>
    }
    '/api/like-comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/like-comment').default>>>>
    }
    '/api/like-post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/like-post').default>>>>
    }
    '/api/unlike-comment': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unlike-comment').default>>>>
    }
    '/api/unlike-post/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/unlike-post/[id]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_supabase/session': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxtjs/supabase/dist/runtime/server/api/session').default>>>>
    }
  }
}
export {}